plugins {
    `java-library`
    `maven-publish`
    id("net.neoforged.moddev")
}

val modId: String = property("mod_id") as String
val minecraftVersion: String = property("minecraft_version") as String
val neoVersion: String = property("neo_version") as String
val releaseChannel: String = providers.gradleProperty("release_channel").map { it.trim() }.getOrElse("")

version = property("mod_version") as String
group = property("mod_group_id") as String

base {
    archivesName = "$modId-$minecraftVersion-neoforge"
}

tasks.named<Jar>("jar") {
    archiveClassifier.set(releaseChannel)
}

// Mojang ships Java 25 to end users in 26.2, so mods should target Java 25.
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets {
    main {
        resources {
            // Include resources generated by data generators.
            srcDir(rootProject.file("src/generated/resources"))

            // Exclude common development only resources from finalized outputs
            exclude("**/*.bbmodel") // BlockBench project files
            exclude("**/.cache")    // datagen cache files
        }
    }

    // Game tests need a running server and must not ship: they register ids into real registries.
    // Stonecutter wires every source set's directories itself; only the classpath needs linking.
    create("gametest") {
        compileClasspath += sourceSets.main.get().output
        runtimeClasspath += sourceSets.main.get().output
    }
}

configurations {
    named("gametestImplementation") { extendsFrom(configurations.implementation.get()) }
    named("gametestRuntimeOnly") { extendsFrom(configurations.runtimeOnly.get()) }

    // 'localRuntime' declares runtime-testing-only dependencies that dependents never inherit.
    create("localRuntime")
    named("runtimeClasspath") { extendsFrom(configurations["localRuntime"]) }
}

repositories {
    mavenCentral()
}

neoForge {
    version = neoVersion

    accessTransformers.publish(rootProject.file("src/main/resources/META-INF/accesstransformer.cfg"))

    validateAccessTransformers = true

    addModdingDependenciesTo(sourceSets["gametest"])

    mods {
        create(modId) {
            sourceSet(sourceSets["main"])
            sourceSet(sourceSets["gametest"])
        }
    }

    val runsRoot = layout.projectDirectory

    runs {
        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
        }

        create("client") {
            client()
            devLogin = true
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
            gameDirectory = runsRoot.dir("run/client")
        }

        create("server") {
            server()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
            programArgument("--nogui")
            gameDirectory = runsRoot.dir("run/server")
        }

        create("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
            gameDirectory = runsRoot.dir("run/gameTestServer")
        }

        create("clientData") {
            clientData()
            programArguments.addAll("--mod", modId,
                    "--all",
                    "--output", rootProject.file("src/generated/resources/").absolutePath,
                    "--existing", rootProject.file("src/main/resources/").absolutePath)
            gameDirectory = runsRoot.dir("run/clientData")
        }
    }

    // Runs `test` through FML, or anything touching BuiltInRegistries has no loader.
    unitTest {
        enable()
        testedMod = mods.named(modId).get()
    }
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.11.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    useJUnitPlatform()
}

val replaceProperties = mapOf(
    "minecraft_version" to minecraftVersion,
    "minecraft_version_range" to property("minecraft_version_range") as String,
    "neo_version" to neoVersion,
    "mod_id" to modId,
    "mod_name" to property("mod_name") as String,
    "mod_license" to property("mod_license") as String,
    "mod_version" to property("mod_version") as String,
)

tasks.withType<ProcessResources>().configureEach {
    inputs.properties(replaceProperties)

    filesMatching(listOf("META-INF/neoforge.mods.toml")) {
        expand(replaceProperties)
    }

    // The Fabric half of the metadata never ships in a neoforge jar.
    exclude("fabric.mod.json")
    exclude("chronoclones.accesswidener")
    exclude("chronoclones.fabric.mixins.json")
}

publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri(rootProject.layout.projectDirectory.dir("repo"))
        }
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}
