plugins {
    `java-library`
    id("dev.kikugie.loom-back-compat")
}

stonecutter {
    // Must mirror build.neoforge.gradle.kts exactly: replacements rewrite the shared source
    // in place, so every node has to agree on the rename table.
    replacements.string(current.parsed < "26") {
        replace("net.minecraft.client.renderer.rendertype.RenderTypes", "net.minecraft.client.renderer.RenderType")
        replace("RenderTypes.", "RenderType.")
        replace("GuiGraphicsExtractor", "GuiGraphics")
        replace("Identifier", "ResourceLocation")
        replace("ContainerInput", "ClickType")
        replace("EntitySpawnReason.", "MobSpawnType.")
        replace("centeredText(", "drawCenteredString(")
        replace(".text(font", ".drawString(font")
        replace("fakeItem(", "renderFakeItem(")
        replace("setScreenAndShow(", "setScreen(")
        replace("net.minecraft.world.entity.player.PlayerSkin", "net.minecraft.client.resources.PlayerSkin")
        replace("extractContents(", "renderWidget(")
        replace("extractLabels(", "renderLabels(")
        replace("getGameProfile().name()", "getGameProfile().getName()")
        replace("snapTo(", "moveTo(")
    }
}

val modId: String = property("mod_id") as String
val minecraftVersion: String = property("minecraft_version") as String
val fabricLoaderVersion: String = property("fabric_loader_version") as String
val fabricApiVersion: String = property("fabric_api_version") as String
val releaseChannel: String = providers.gradleProperty("release_channel").map { it.trim() }.getOrElse("")

version = property("mod_version") as String
group = property("mod_group_id") as String

base {
    archivesName = "$modId-$minecraftVersion-fabric"
}

// No remapJar here: the unobfuscated era has nothing to remap, so the plain jar is the artifact.
tasks.named<Jar>("jar") {
    archiveClassifier.set(releaseChannel)
}

// Mojang ships Java 25 to end users in 26.2, so mods should target Java 25.
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets {
    main {
        resources {
            // Include resources generated by data generators (run from the neoforge node).
            srcDir(rootProject.file("src/generated/resources"))

            exclude("**/*.bbmodel")
            exclude("**/.cache")
        }
    }

    // Game tests need a running server and must not ship: they register ids into real registries.
    // Stonecutter wires every source set's directories itself; only the classpath needs linking.
    create("gametest") {
        compileClasspath += sourceSets.main.get().compileClasspath + sourceSets.main.get().output
        runtimeClasspath += sourceSets.main.get().runtimeClasspath + sourceSets.main.get().output
    }
}

loom {
    accessWidenerPath = rootProject.file("src/main/resources/chronoclones.accesswidener")

    mods {
        create(modId) {
            sourceSet(sourceSets["main"])
        }
        // Its own dev mod: it carries a second fabric.mod.json whose entrypoint registers the
        // test functions, which the loader would ignore inside the main mod's group.
        create("chronoclones_gametest") {
            sourceSet(sourceSets["gametest"])
        }
    }

    runs {
        named("client") {
            client()
            configName = "Fabric Client"
            runDir = "run/client"
        }
        named("server") {
            server()
            configName = "Fabric Server"
            runDir = "run/server"
        }
        create("gametest") {
            server()
            configName = "Fabric GameTest Server"
            runDir = "run/gametest"
            vmArg("-Dfabric-api.gametest")
            source(sourceSets["gametest"])
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly("org.jspecify:jspecify:1.0.0")
    "gametestCompileOnly"("org.jspecify:jspecify:1.0.0")
    testCompileOnly("org.jspecify:jspecify:1.0.0")

    minecraft("com.mojang:minecraft:$minecraftVersion")
    // 26.x is the unobfuscated era: no mappings block; loom-back-compat handles the rest.
    modImplementation("net.fabricmc:fabric-loader:$fabricLoaderVersion")
    modImplementation("net.fabricmc.fabric-api:fabric-api:$fabricApiVersion")

    testImplementation(platform("org.junit:junit-bom:5.11.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    // Boots the loader inside JUnit so registries exist when tests touch game objects.
    testImplementation("net.fabricmc:fabric-loader-junit:$fabricLoaderVersion")
}

tasks.test {
    useJUnitPlatform()
    // Picks up GameBootstrapExtension, which boots the vanilla registries before test classes.
    systemProperty("junit.jupiter.extensions.autodetection.enabled", "true")
}

val replaceProperties = mapOf(
    "minecraft_version" to minecraftVersion,
    "minecraft_version_range" to property("minecraft_version_range") as String,
    "fabric_loader_version" to fabricLoaderVersion,
    "mod_id" to modId,
    "mod_name" to property("mod_name") as String,
    "mod_license" to property("mod_license") as String,
    "mod_version" to property("mod_version") as String,
)

tasks.withType<ProcessResources>().configureEach {
    inputs.properties(replaceProperties)

    // Mixin before 0.8.7 does not know JAVA_25; the mixin classes themselves are fine.
    if (stonecutter.current.parsed < "26") {
        filesMatching("*.mixins.json") {
            filter { line -> line.replace("\"compatibilityLevel\": \"JAVA_25\"", "\"compatibilityLevel\": \"JAVA_21\"") }
        }
    }

    // assets/<ns>/items item-model definitions are a 1.21.4+ format; equipment assets are 1.21.2+.
    if (stonecutter.current.parsed < "1.21.2") {
        exclude("assets/*/items/**")
        exclude("assets/*/equipment/**")
    }

    // Plain-string ingredients arrived in 1.21.2; older parsers want the {"item": id} object.
    if (stonecutter.current.parsed < "1.21.2") {
        filesMatching("data/*/recipe/*.json") {
            filter { line -> line.replace(Regex("\"([A-Z])\": \"([a-z0-9_.:/-]+)\""), "\"$1\": { \"item\": \"$2\" }") }
        }
    }

    filesMatching(listOf("fabric.mod.json")) {
        expand(replaceProperties)
    }

    // The NeoForge half of the metadata never ships in a fabric jar.
    exclude("META-INF/neoforge.mods.toml")
    exclude("META-INF/accesstransformer.cfg")
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}
